// services/nuxt/src/app/pages/sign-up.vue
<script setup lang="ts">
import { reactive } from 'vue'
import { env } from '@/data/env'

const form = reactive({
  username: '',
  password: '',
})

async function onSubmit() {
  await $fetch(`${env.API_URL}/user/register/`, { method: 'POST', body: form })
}
</script>

<template>
  <main class="flex justify-center h-screen items-center">
    <form
      @submit.prevent="onSubmit"
      class="flex flex-col p-4 border border-black"
    >
      <label for="username" class="mb-1">Username</label>
      <input
        v-model="form.username"
        id="username"
        type="username"
        autocomplete="username"
        required
        class="p-1 border border-black mb-2"
      />
      <label for="password" class="mb-1">Password</label>
      <input
        v-model="form.password"
        id="password"
        type="password"
        autocomplete="current-password"
        required
        class="p-1 border border-black mb-2"
      />
      <button type="submit" class="p-1 border border-black rounded-lg mt-2">
        Submit
      </button>
    </form>
  </main>
</template>

// apps/next_js/src/app/sign-up/page.tsx
'use client'

import { signUp } from './../../lib/auth-client'

export default function SignUpPage() {
  return (
    <form
      onSubmit={async e => {
        e.preventDefault()

        const formData = new FormData(e.currentTarget)

        const email = formData.get('email')
        const password = formData.get('password')
        const name = formData.get('name')

        if (
          typeof email !== 'string' ||
          typeof password !== 'string' ||
          typeof name !== 'string'
        ) {
          return
        }

        console.log(email)
        console.log(password)
        console.log(name)

        await signUp.email({ email, password, name })

        console.log(data)
        console.log(error)
      }}
      className="flex flex-col items-center justify-center h-screen"
    >
      <label htmlFor="email">email</label>
      <input name="email" type="email" />
      <label htmlFor="password">password</label>
      <input name="password" type="text" />
      <label htmlFor="name">name</label>
      <input name="name" type="text" />
      <button type="submit">submit</button>
    </form>
  )
}
